extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  attributes:
    actions:
      - key: region
        value: west
        action: insert

exporters:
  debug:
  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
  # Recommended Configuration:
  # It is highly recommended to use the connection string which includes the InstrumentationKey and IngestionEndpoint
  # This is the preferred method over using 'instrumentation_key' alone.
  azuremonitor:

service:
  extensions: [ health_check, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch, attributes ]
      exporters: [ otlp/jaeger, azuremonitor ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus, azuremonitor ]
    logs:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ loki, debug, azuremonitor ]