global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
#  - job_name: opentelemetry.logging
#    static_configs: 
#      - targets: 
#          - 'opentelemetry.logging:8080'
  - job_name: otel-collector
    static_configs:
      - targets:
          - 'otel-collector:8889'